name: slant
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  adobe_xd: ^2.0.1
  convex_bottom_bar: ^3.0.0
  diamond_bottom_bar: ^1.0.0
  animated_bottom_navigation_bar: ^0.3.2
  camera: ^0.9.4+18
  auto_size_text: ^3.0.0
  percent_indicator: ^4.0.0
  page_transition: ^2.0.5
  provider: any
  # geolocator: ^8.2.0
  # geocoding: ^2.0.4
  hashtagable: ^2.0.2+1
  better_player: ^0.0.81
  firestore_search: ^0.1.9
  video_thumbnail: ^0.5.0
  delayed_display: ^2.0.0

  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.11
  firebase_auth: ^3.3.12
  firebase_core: ^1.14.0
  firebase_storage: ^10.2.10
  preload_page_view: ^0.1.6
  get: ^4.6.1
  image_picker: ^0.8.4+11
  expandable: ^5.0.1
  expandable_text: ^2.3.0
  expand_widget: ^2.1.0
  timeago: ^3.2.2
  # video_compress: ^3.1.0
  video_compress:
      git:
        url: https://github.com/jonataslaw/VideoCompress.git
        ref: master
  cached_video_player: ^2.0.0-dev.1

  rename: ^2.0.1
  form_field_validator: ^1.1.0
  flutter_facebook_auth: ^4.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
